services:
  task1:
    image: hiirsh/tasks:task1
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - SERVICES=s3
      - MYSQL_HOST=<mysql_host_name>
      - MYSQL_USERNAME=<mysql_username>
      - MYSQL_PASSWORD=<mysql_password>
      - MYSQL_DATABASE=<mysql_database>
      - AWS_S3_ENDPOINT=<s3_endpoint>
      - AWS_S3_BUCKET_NAME=<s3_bucketname>
    volumes:
      - ./.temp/
# services:
#   task1:
#     image: hiirsh/tasks:task1
#     privileged: true
#     ports:
#       - "8080:8080"
#     environment:
#       - DEBUG=1
#       - DATA_DIR=/var/lib/localstack
#       - SERVICES=s3
#       - MYSQL_HOST=localhost:3307
#       - MYSQL_USERNAME=root
#       - MYSQL_PASSWORD=1234
#       - MYSQL_DATABASE=goza_tasks
#       - AWS_S3_ENDPOINT=http://localhost:4566
#       - AWS_S3_BUCKET_NAME=uploads
#   volumes:
#   - ./.temp/
