# version: "3.8"

# services:
#   localstack:
#     container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
#     image: localstack/localstack
#     ports:
#       - "127.0.0.1:4566:4566"            # LocalStack Gateway
#       - "127.0.0.1:4510-4559:4510-4559"  # external services port range
#     environment:
#       - DEBUG=${DEBUG-}
#       - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
#       - DOCKER_HOST=unix:///var/run/docker.sock
#     volumes:
#       - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
#       - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  localstack-net:
    name: localstack-net
    driver: bridge

services:
  localstack:
    image: localstack/localstack
    privileged: true
    networks:
      - localstack-net
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - DEBUG=1
      - DATA_DIR=/var/lib/localstack
      - SERVICES=s3
      # - AWS_DEFAULT_REGION=us-east-1
      # - AWS_ACCESS_KEY_ID=testUser
      # - AWS_SECRET_ACCESS_KEY=testAccessKey
    volumes:
      - ./.temp/localstack:/var/lib/localstack
